### ISSUE TITLE
Night Vision Module generates power

### ISSUE THREAD

**Issue by BlackBeltPanda** [budak7273/ArmorModules#10]
**Describe the bug**
When the Night Vision Module is equipped, it adds 5MWs to the suit's power balance.

**To Reproduce**
Steps to reproduce the behavior: Equip the Night Vision Module

**Expected behavior**
The Night Vision Module should deduct 5MWs from the suit's power balance.

**Multiplayer?**
Only tested in Single Player.

**Screenshots**
![FactoryGame-Win64-Shipping_UEOvHPrcGD](https://user-images.githubusercontent.com/5866087/104854936-8eaf5400-58d7-11eb-9d6c-0c10895b20fb.png)

**Comment by budak7273** [comment]
Thanks for catching this! I have fixed it in 3fea853, but I might not push it in an update for a while. Enjoy the free power until then.

External Power is in a weird place right now. It is intended to be used as power cost for "suit attachments" that attach another actor to the suit, but no one has really written any suit attachments yet (other than this Night Vision module by Nog, which I messed up the power cost on)

External Power might be going away in the next version of PowerSuit - we might end up changing how the power balance works to better separate power consumption and power generation.
