### ISSUE TITLE
No possibility to change the default keys.

### ISSUE THREAD

**Issue by Maazter** [budak7273/ArmorModules#11]
Firstly I just want to say, Nice Mod and great work! I am looking forward to using this around the map whilst exploring :-)

As the title says...In my case, I would like to be able to change the thrust key from being the space bar, the reason being is that I do not use the default keys in any of my games, I always use the arrow keys and the surrounding keys for various other commands, this makes it incompatible with my gaming style to be able to use the thrust boots in the suit.

Is there a config that can be changed or are you working on the mod using user defined keys?

Regards.

M.

**Comment by budak7273** [comment]
Thanks for the report! I'm glad you're enjoying the mod so far.

The keybinds are controlled by the base PowerSuit mod, so it would be implemented in that mod and not this one.

The next SML version will release some extra keybind features which we are waiting on to implement key rebinding. You can read more [here](https://github.com/Nogg-aholic/PowerSuit/issues/4#issuecomment-742450934).

**Comment by Maazter** [comment]
Hi, Thank you for the quick feedback, so better to wait for the next SML version then? if so may I ask if those will include mouse binding?

Again thank you for your help.

M.

**Comment by budak7273** [comment]
I'm not certain. I would assume they are treated like any other key? Someone on the Discord might know.

**Comment by Maazter** [comment]
I would assume so, but as you may know, assuming anything can lead to problems :-) yea...I'll have a brows around and see if anyone came across this!

Thnx again for the feed back.

M.

**Comment by budak7273** [comment]
SML keybind support added in Update 4 release of the mod
