### ISSUE TITLE
Modules get deleted when player dies while wearing biofuel power suit

### ISSUE THREAD

**Issue by ExZiByte** [budak7273/ArmorModules#12]
**Describe the bug**
Any installed module on the biofuel power suit get deleted if a player dies while using the suit
**To Reproduce**
Create a biofuel power suit
Install modules
Die
Retrieve items from death crate
Open modules inventory of biofuel power suit

**Expected behavior**
Modules not to be deleted if player dies

**Multiplayer?**
If you're playing in multiplayer, if it affects host or clients, etc.
Playing in a world that was previously used for multiplayer but the other players quit playing prior to me unlocking the power suit milestone and all the subsequently required milestones for the modules. Affects host don't know if it affects clients also

**Comment by budak7273** [comment]
This is an inconsistent issue that we've been trying to track down for a while now.

Does this happen consistently, every time you die? I have died countless times in my test world, but only rarely do the contents of my armor vanish.

How far away from your HUB are you when you die?

I would appreciate it if you could send your save file (and possible mod loader profile) for further testing.

**Comment by ExZiByte** [comment]
It doesn't happen all the time but now that you mentioned distance was a possible culprit everytime it did happen I was about 1 km from the HUB or more 

While I was typing the issue I was also trying to record a video of it happening and it didnt happen both times I tried but at the time i was less then 500 meters from the HUB

I can get you the save file and mod loader profile when I get home from work in about 8 hours

**Comment by budak7273** [comment]
I suspect that it has to do with distance - maybe the body being in another map tile or something. But at the same time, I have died and lost inventory contents while less than 50 meters from the hub before, so I'm not really sure what's going on with it.

**Comment by budak7273** [comment]
Should be resolved with the Update 4 release of the mod, which changes the owner of the suit to no longer be the character/pawn (don't remember which at the moment) which is deleted on death, causing the problem.
