### ISSUE TITLE
[Suggestion] Still some issues with Biofuel module costs.

### ISSUE THREAD

**Issue by Vassi** [budak7273/ArmorModules#14]
[#7] Previously reported an issue with the biosuit itself but even though that is now sensible to its tier to build it's still unusable at tier 2 for a couple of reasons:

Module Base Component
All versions of this require heavy modular frames. Which aren't craftable until tier 4.

Integrated Blade Runners:
In addition to the module base component requirement, these still want 50 motors.

Thrust Boots Module:
Module base component requirements.
Precision thrusters require pipes, which are tier 3.

Bio Reactor Module:
Module base component requirements.
Steel pipes.

Suggestion:
I love that I can have these two this early in the game. Obviously without the boots there is no reason for this suit to exist as I can just use the blade runners on their own. 

If the requirements must stay this way, maybe just move these milestone to tier 4?

Also I suggest making the boots use the fuel a little more aggressively. I feel like I can get too much lift out of these (especially when combined with the speed of the runners) and expected them to really just help me fall safely and basically bunny hop longer distances, not necessarily be able to climb as much as I can.

**Comment by budak7273** [comment]
Thanks for the feedback - I really appreciate it. 

The content is accessible as early as T3 to allow people to use the parts that they find at crash sites to craft it "early," rewarding exploration. Based on my own gameplay, it is feasible to gather that many steel pipes and motors from crash sites starting out. Heavy modular frames are intentionally a bit pricy, but once you make a few, the alternates allow you to use other stuff instead.

I should probably add a note about this to one of the helper items, or maybe the ADA message. Which place do you think more people would notice?

Regarding the thrust boots - how many full size foundations are you able to ascend with them? I am wondering if there are still inconsistencies with jetpack thrust across different peoples' computers.

**Comment by Vassi** [comment]
I see. I guess that makes sense, but since it's not explained anywhere else. It just feels very odd to get the suit, be able to immediately build it, then discover you can't do anything with it because the modules are a tier away (assuming you've played the game before and know what Motors/Heavy Modular frames are)

Thrust boots I can easily climb four walls worth starting from a jump. I do get that the momentum is way more stalled than regular jetpack, and it's definitely not terrible or anything, I just thought I would mention it if the intent was to make them more limited.

Either way thank you for the excellent work!

**Comment by budak7273** [comment]
Do you have a suggestion for where it could be explained? I'm not sure where best to put it that would result in people actually seeing it. Maybe one of those 'helper' items in the hub?

Thanks for the heads up on the thrust boots. They'll have to be reworked for U4 regardless, since Nog is changing how the flight code works again.

EDIT: Turns out I already have it in the description of the 'module tutorial' item. It could really benefit from being somewhere else as well, then.

**Comment by budak7273** [comment]
Closing this since costs were entirely reworked in the Update 4 version of the mod, addressing this problem.
