### ISSUE TITLE
[Suggestion] update for sml v 3.1.1

### ISSUE THREAD

**Issue by Oberon1989** [budak7273/ArmorModules#15]
Hello, I used your Power Suit modules mod before update 4. I would like to continue using it again but unfortunately it is not in the list of compatible mods for version 3.1.1. Will your mod be updated for the current version of the game?

**Comment by budak7273** [comment]
You can see find on how to download an early release of the Update 4 compatible version of the mod at the top of the page here: https://ficsit.app/mod/BezrE8aswqXLRX

I'm in the process of significantly restructuring the mod and adding a *lot* more features, which is part of why it's taking so long to complete.

I'd like to hear your feedback on the changes so far - I should have another early release out in the next few days that introduces even more features.

**Comment by budak7273** [comment]
Closing this since the mod has been updated

**Comment by Oberon1989** [comment]
Thank for your work in this mod.

пт, 30 июл. 2021 г., 9:11 Rob B ***@***.***>:
