### ISSUE TITLE
Hud Disappears when switching hand item

### ISSUE THREAD

**Issue by Shad0wlife** [budak7273/ArmorModules#17]
**Describe the bug**
When having multiple handheld items equipped the HUD disappears. I only managed to make it reappear when un- and reequipping the power armor. Switching back to the original handheld item does not help and only shows the empty item panel.

**To Reproduce**
1. Have multiple handheld items equipped.
2. Equip power armor (you now should have the HUD overlaying the handheld item panel)
3. Scroll (or otherwise change your handheld item)
4. The HUD is now gone
5. Only way to restore hud (that I found) is to reequip the power armor - draining fuel unneccessarily if the Armor has a fuel burner equipped.

**Expected behavior**
Changing the Handheld item does not remove the HUD.
Or at least the Handheld item which had the hud in the first place shows it again when selected.

**Multiplayer?**
Not tested.

**Screenshots**
Available by request. But repro should be easy.

**Additional context**
If this needs to be placed in Nog's repo, please tell me. But since this mod's custom HUD is affected I decided to just place this here for now.

If you crashed, please attach your crash generated by the launcher to this report.
No Crash.

**Comment by budak7273** [comment]
Unless I'm doing something wrong, it isn't happening on my end. See the video below.

https://streamable.com/3gp8x2

What other mods do you have installed? I should really add that to the bug template.

Which hand items were you using? Perhaps they do HUD modifications of their own, if they're from other mods.

**Comment by budak7273** [comment]
Any updates on this? What suit did you experience the issue with? Someone reported a similar issue but seemingly only while wearing the Mk2 suit (which should not make a difference).

**Comment by Shad0wlife** [comment]
Sorry, I'm on holiday, so I can only tell from memory.
The items I switched between were the default sword, chainsaw and inhaler. The suit was the biofuel suit.
Istalled mods include Smart, Refined Power, Conveyor Wall mounts, Pipe Wall Mounts, Grid Marker, Ficsmas Forever and the full Power Armor pack.
There's probably 1 or 2 more minor ones which I forgot, but No items or Recipes I think.

**Comment by budak7273** [comment]
This should have been fixed by PowerSuit update 0.7.0 or so. Check the patch notes for which specific version has fixed it.
