### ISSUE TITLE
Fuel type consumption changes [Suggestion]

### ISSUE THREAD

**Issue by Alighierian** [budak7273/ArmorModules#2]
Having only briefly used the Mk1 suit with the Jetpack/flight module, I ran into something of an annoyance: It prioritizes Solid Biofuel over Turbofuel if both are present on load. It will first consume the initial charge it still had stored, after which it seems to revert to the first viable fuel, preferring Bio rods over Fuel, turbo or normal.
To get it to use liquid fuel again, I first have to remove the solid biofuel, empty the current charge, and once it switched over, pick up the biofuel again.

Edit: this seems to be temporary to boot, as it goes right back to biofuel rods as soon as the current turbofuel charge runs out.

The main issue, in this case, stems from the chainsaw needing that type of fuel, as it can't run on liquid fuel, making it pretty annoying when the jetpack chugs all of it.

Would it be possible to make it prefer the most potent fuel, or make it ignore the biofuel rods altogether?

**Comment by budak7273** [comment]
Thanks for the report! 

It definitely makes sense for the suit to prioritize turbofuel over the solid biofuel. Not only is turbofuel worth more fuel charge per item, the usage of chainsaw fuel instead would be quite annoying, as you said. 

The fuel selection logic is done by the suit, and is controlled by the PowerSuit side of the mod, so I passed this along to Nog. He has changed the order; it will be out in the next update.

**Comment by Alighierian** [comment]
Thanks, I'll look forward to it.

**Comment by budak7273** [comment]
The new version of PowerSuit was released today that should have fixed the issue. I'll close this for now, but feel free to reopen if it isn't actually fixed.
