### ISSUE TITLE
Integrated blade runners yeet player into space

### ISSUE THREAD

**Issue by Avexuzz** [budak7273/ArmorModules#21]
## Describe the bug

Integrated blade runners launch player with absurd vertical speed if bumped on top of some mobs.

## To Reproduce

1. Equip Powersuit (tested with Biofuel suit).
2. Equip Integrated Blade Runners.
3. Jump on top of Hog/Spitter/Doggo to get bumped off.
4. Get launched to space causing immediate death, mostly without even a death crate spawning.

## Expected behavior

Get a small bump.

## Screenshots or Videos

https://youtu.be/VBGlDrhu7kI
(Tested in Doggo cave, so died crashing in cave walls, not to top world border).

## Other Mods

-Power suit
-Modpack: All PowerSuit Modules
-Refined Power
-Faster Manual Crafting
-Mk++
-Fluid AWESOME Sink
-Covered Conveyor Belt
-Smart!
-X3 Better Vehicles & Drones [MP]
-X3 Roads [MP]
-Pak Utility Mod
-Inventory Slots +150

## Additional context

Never happens without any Blade Runners or with vanilla Blade Runners. Seems not to happen on Space Whales.

**Comment by budak7273** [comment]
Thanks for the report. I especially appreciate the detailed reproduction steps and video.

We've had reports of this happening while people were flying and getting hit by spitters, and suspected it had to do with the flight logic we don't have control over (the suit uses base game Hover Pack flight) But we've never heard of it happening just while landing on creatures.

I am very busy at the moment with other commitments, so I won't be able to look into this for a bit, unfortunately.

Does the same problem occur if you use any of the other ground speed enhancing modules, for example, the Fuel Runners? Perhaps a particular stat the module is awarding is to blame - maybe the one involved in step height. The Fuel Runners do not have that stat, so it will be interesting to see if they have the problem as well.

**Comment by Avexuzz** [comment]
Tried all simillar "boots" modules from "Pioneer mobility" tab (Fuel Runners, Walking and Sprinting Compensators MK1, Exoskeleton MK1) and no - they are not affected and work fine. Except WIP Jump Thrusters - this module also grants highly increased vertical speed when landing on mob.

UPD: Thrust Boots from Flight Modules are also bugged. Seems like jump height bonus works not as expected on small creatures.

**Comment by budak7273** [comment]
Mitigated in PowerSuit 1.1.1
