### ISSUE TITLE
Issue with the Right-Alt shortcut.

### ISSUE THREAD

**Issue by Tropelage** [budak7273/ArmorModules#22]
## Describe the bug
Hello, ever since the last update 1.3.0 I have not been able to either get in the configuration of the modules from the pockets screen, or the Right-Alt key.

## To Reproduce

Steps to reproduce the behavior. If it involves content from other mods, be sure to state what.

## Expected behavior

Expect to be able to configure the modules.

## Multiplayer?

If you're playing in multiplayer, pleaste state if it affects host or clients, etc.

## Screenshots or Videos

If applicable, add screenshots or a video to help explain your problem. I suggest Streamable as video uploading service and [ShareX](https://getsharex.com/) as an image/video capture tool, if you need one.

## Other Mods

![image](https://user-images.githubusercontent.com/71179003/135159325-8ea4785c-37aa-4100-93ef-f88328a6668f.png)

## Additional context

If you crashed, please attach your crash generated by the launcher to this report.
![](https://cdn.discordapp.com/attachments/555782140533407764/738104443849015387/unknown.png)

**Comment by budak7273** [comment]
Thanks for the report!

Based on the scroll bar in your screenshot, there are a few other mods that you have installed that aren't on that screenshot. Could you please share the full mods list?

There are a number of mods that are known to prevent the config screen from opening (Game Time, Hotswap Equipment, and Build Menu Organizer should be listed in the warning at the top of the mod page). Do you have any of those mods installed?

**Comment by Tropelage** [comment]
Thank you for your response. I believe I have "Game Time", installed. I can un-install and try it.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Tropelage** [comment]
Thank you Rob. It appears the GameTime add-on is the culprit in my case. I removed it and now I am able to get to my suit config.

Kind regards,

Oscar C

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by budak7273** [comment]
Thanks. In the future, I should have some time to track down why these mods actually prevent the window from opening. I will close down this issue once that is fixed.

**Comment by budak7273** [comment]
This should be fixed as of 0.8.3
