### ISSUE TITLE
suit can go into its own storage compartment

### ISSUE THREAD

**Issue by boneskull** [budak7273/ArmorModules#23]
## Describe the bug

When body equipment stored in storage compartment (e.g., a jetpack), shift-clicking the body equipment will swap it with your current suit.  The suit ends up in its own storage compartment.

## To Reproduce

1. Get a jetpack and a power suit
2. Install storage compartment
3. Equip power suit
4. Put jetpack in storage compartment
5. Shift-click on jetpack in storage compartment
6. _poof_ goes the jetpack

## Expected behavior

The the current suit should not be allowed in its own storage compartment.  There are a handful of strategies to disable (e.g. shift-clicking from storage compartment does not equip/swap, but rather moves into main inventory), but I don't know what's feasible--esp. given the main inventory can be full.  Perhaps drop the equipment on the ground if there is no room in inventory.  Or drop the suit on the ground if it was to be swapped into its storage compartment.

(it may have actually dropped on the ground, and this has already been fixed, but I didn't see it)

## Multiplayer?

No

## Other Mods

Yes; will post if you cannot reproduce

**Comment by budak7273** [comment]
Thanks for the report!

Nice catch, I totally forgot to add any sort of blacklist to the slots. It could be a while before I have the time to fix this, though. I will probably blacklist all suits and storage compartment modules.

Thank you for pointing out the shift click case. I'm not certain what would happen if I did set up filters (ex to prevent suits from being stored in there) and tried that - I wonder if it would end up bypassing the filter. I'll have to try that out later.

**Comment by budak7273** [comment]
This is now fixed as of 3.5.0. Thanks again! It drops invalid items on the ground when you try to put them in.
