### ISSUE TITLE
PowerSuit Logistic Modules: Pocket Dimension Duplication

### ISSUE THREAD

**Issue by HylianLZ** [budak7273/ArmorModules#24]
## Describe the bug

Telling a Pocket Dimension to keep more stacks in your inventory than you have in the pocket dimension will create free duplicate items/ full stacks.

## To Reproduce

Equip a Pocket Dimension (Only tested with mk2) into a PowerSuit, Have only one stack of any test item in your inventory, doesn't need to be full. Equipment works too. Set the PD filter to that stack, turn the PD off, Move the stack to the PD, increase amount to be in inventory, turn the PD on. It will put as many full stacks of that item as you set in the amount.

## Expected behavior

Expect the PD to return to my inventory only the items I currently have in storage.

## Other Mods

PowerSuit Logistic Modules
PowerSuit
Modpack: All PowerSuit Modules
PSM: Mobility
PSM: Fresh from R&D
PSM: Pioneer Protection
PSM: Flight
PSM: Power Generation
PSM: Suit Regulation
PowerSuit Modules
Refined Power
Modular UI
RefinedRDLib
Faster Manual Crafting
Underground Belts
MAM Enhancer
Smart!
MallLib
Micro Manage
Small Storage Container
Full Health Regeneration
Storage Teleporter

## Additional context

Not crashing, just cheaty without cheats enabled. Running on latest official version of everything according to SMM.

**Comment by budak7273** [comment]
Thanks for the report!

I was able to reproduce this issue in game following the steps you provided.

I do not have the time to fix this at the moment, but @Nogg-aholic , who created that sub-mod, might.  Otherwise, this will probably be fixed when the mod is updated to U5.

**Comment by HylianLZ** [comment]
No worries, it's not breaking anything. Just wanted to make it known.

**Comment by budak7273** [comment]
This is now fixed as of 3.3.0. Thanks again!

**Comment by budak7273** [comment]
I meant 3.5.0, whoops
