### ISSUE TITLE
Overdraw Alarm Sounds and will not turn off without restarting the game.

### ISSUE THREAD

**Issue by DrakenKiele** [budak7273/ArmorModules#25]
## Describe the bug

Suit starts to overdraw, I go straight to the ground to make adjusments.  Alarm does not shot off, even if I remove the suit and place it in a container.  Must restart game.  The issue is repeatable, even with different configs.  Had some of Nogs mods installed in the suit, thought that was the prob.  Removed them and restarted the game.  Same thing happens. Also, there is no config screen, just the tab.  Click it and the inventory UI closes, with nothing else opening.

## To Reproduce

explained above.

## Multiplayer?

I'm in single player game.

## Screenshots or Videos

If applicable, add screenshots or a video to help explain your problem. I suggest Streamable as video uploading service and [ShareX](https://getsharex.com/) as an image/video capture tool, if you need one.

## Other Mods

What other mods do you have installed? Set your SMM to Show 'Enabled' mode, which lists all mods, including dependencies, and put a screenshot here. Alternatively, export and attach your SMM profile, or simply list what mods you have installed.

## Additional context

If you crashed, please attach your crash generated by the launcher to this report.
![](https://cdn.discordapp.com/attachments/555782140533407764/738104443849015387/unknown.png)

**Comment by budak7273** [comment]
Thanks for the report!

The issue with the configs screen not opening is a known incompatibility with a few mods, namely Game Time, Hotswap Equipment, and Build Menu Organizer. More info in #22 and on the top of the [mod page](https://ficsit.app/mod/BezrE8aswqXLRX). Do you have any of those installed? If so, try removing them and then opening the config tab.

Regarding the sound looping problem - what modules are installed in your suit? I haven't been able to reproduce this issue in the past, so I'm guessing it is tied to a specific module somehow. Next time the sound looping problem occurs, try taking modules out of the suit one at a time and seeing if that stops the loop.

**Comment by DrakenKiele** [comment]
Thanks.  Will give your suggestions a try and report back soon.
Here is my mod list.
[modded.smmprofile.txt](https://github.com/budak7273/ArmorModules/files/7451299/modded.smmprofile.txt)

**Comment by budak7273** [comment]
This should be resolved as of 0.8.3
