### ISSUE TITLE
Build Module doesn't request for consecutive builds

### ISSUE THREAD

**Issue by Malkierian** [budak7273/ArmorModules#26]
I have the Build Module from Logistics in my suit, as well as a range extender. I have more than enough power. However, when I go to build something I don't have enough inventory for, if I build one and then try to build again without exiting build mode, the module requests enough for the first one, but it doesn't request the required items for the second and subsequent ones. I have to hit escape or switch blueprints really quick. This happens for vanilla buildings as well as mod buildings. It also happens if I have enough for several builds and then run out of parts without exiting or swapping build like I mentioned before. Happens with no other mods installed, too.

**Comment by budak7273** [comment]
Thanks for the report!

I do not have the time to investigate this further at the moment, but @Nogg-aholic , who created that sub-mod, might. Otherwise, this will probably be fixed when the mod is updated to U5.

**Comment by budak7273** [comment]
This is fixed by now and I forgot to close the issue since it wasn't on the Logistic Modules repo
