### ISSUE TITLE
[Suggestion]Update integrated hazmat suit tooltip to indicate it doesn't protect against toxic gas

### ISSUE THREAD

**Issue by hoylemd** [budak7273/ArmorModules#28]
Please read the [Future Update Plans]( https://github.com/budak7273/ArmorModules/blob/master/README.md#future-update-plans-in-no-particular-order) and Won't Add section of the mod page before continuing

<img width="352" alt="inthazmattooltip" src="https://user-images.githubusercontent.com/569403/166151694-9b912be7-9725-44dd-b34d-bf1da07f7b94.png">

The integrated Hazmat Suit doesn't protect against toxic gas like the vanilla one does.  This seems reasonable, as in vanilla you can't equip both, but you can with PowerSuit.  Unfortunately, the vanilla behaviour led me to expect the powersuit module to work the same way.  The tooltip currently doesn't mention toxic gas directly, but it does reference 'air filtration', which reinforced my expectation that it would protect against toxic gas.

If it's not too much trouble, adding a bit to the tooltip like 

> Note: does not protect against toxic gas, only radiation.

would prevent other players from making the same assumption.

**Comment by budak7273** [comment]
I never actually realized that the vanilla hazmat suit worked on toxic gas as well. It doesn't say so in the vanilla item's tooltip, but the [wiki page](https://satisfactory.fandom.com/wiki/Hazmat_Suit) and my own testing confirms it - apparently it was quietly added in U5 without mention in the patch notes.

The vanilla hazmat doesn't have the gas mask breathing loop sounds when in use either - it seems like the gas protection was added as a bit of an afterthought. Given that they're changing equipment in U6, I wonder if they will decide to undo that change.

I don't think I will add gas functionality to the suit hazmat module, but I will update the tooltip text to mention the lack of gas protection. It could be a while before that update comes out, though.

**Comment by budak7273** [comment]
Fixed in 4.0.0, and they also seem to have removed the vanilla hazmat suit being able to protect against gas as well
