### ISSUE TITLE
Update 6 Support

### ISSUE THREAD

**Issue by mEMPhis002** [budak7273/ArmorModules#29]
## Describe the bug

Game crashed after launching the game

## To Reproduce

Steps to reproduce the behavior. If it involves content from other mods, be sure to state what.
Game crashed everytime when mod PowerSuit Modules Modpack: All Modules is enable in Satisfactory Mod Manager

## Multiplayer?

no

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/109222184/178736659-f0afd422-9c04-44b9-98e9-9bb81b244c59.png)

## Other Mods

Enable 
![image](https://user-images.githubusercontent.com/109222184/178737470-087bee6a-5326-4042-96e6-21bb2a396e06.png)
Disable
![image](https://user-images.githubusercontent.com/109222184/178737572-cc8690f3-2fb2-4919-8a07-0cb222f00970.png)
****

If Mod from the list are disable the Game launch and run properly

## Additional context

If you crashed, please attach your crash generated by the launcher to this report.
![image](https://user-images.githubusercontent.com/109222184/178736659-f0afd422-9c04-44b9-98e9-9bb81b244c59.png)

[FactoryGame.log](https://github.com/budak7273/ArmorModules/files/9102319/FactoryGame.log)

**Comment by budak7273** [comment]
This mod still needs to be updated for Update 6, as stated on the [mod page](https://ficsit.app/mod/ArmorModules). You'll have to stick with Update 5 for now.

**Comment by budak7273** [comment]
Fixed in 4.0.0
