### ISSUE TITLE
suit modules broken

### ISSUE THREAD

**Issue by Straya22** [budak7273/ArmorModules#31]
## Describe the bug
suit modules get deleted after putting in suit expander modules and will delete any new modules going in
## Expected behavior
suit modules should work together as intended with no issues
## Multiplayer?
no
## Other Mods
Mod Name                         Mod Reference                  Version
Additional 300 Inventory Slots   Additional_300_Inventory_Slots 5.0.5
Additional 500 Inventory Slots   Additional500InventorySlots    1.0.4
All Nodes Pure                   AllNodesPure                   1.0.2
AntiRadiation Box forTransport   BoxedUranium                   2.0.2
Area Actions                     AreaActions                    1.6.7
Awesome Points x100              HundredTimesAwesomePoints      1.0.1
Belt and Miner Renewed           bamrenew                       1.1.11
Big Storage Tank and MegaPump    BigStorageTank                 2.0.3
Blueprint Designer Plus          KBlueprintDesignPlus           1.0.2
Build Gun Utilities              BuildGunUtilities              1.7.0
Buildable Resource Nodes Redux   BuildableResourceNodesRedux    2.0.1
Cable Choices +                  AB_CableMod                    0.3.5
Construction Preferences         ConstructionPreferences        1.3.5
Conveyor Wall Hole               WallHoleConveyor               2.0.5
Daisy Chain Everything           DaisyChainEverything           1.0.2
Destructible Deposits            DestructibleDeposits           1.0.4
Destructible Gas Pillars         DestructibleGasPillars         1.0.1
Doors Anywhere                   DoorsAnywhere                  1.0.2
Double Freight Car               DoubleCargoWagon               1.0.1
Duplicators                      Duplicator                     1.0.9
Easy Refinery                    EasyRefinery                   2.0.1
EasyAlt Recipes                  EasyAltRecipes                 1.1.5
Efficient Resources Cheat        EfficientResources             2.0.3
Expanded Hover Range             HoverPackPoleRange             1.0.4
Explorer with Turrets            TurretCar                      1.0.3
Feld Artillerie                  TrueNukes                      1.1.0
Flex Splines                     FlexSplines                    1.0.10
Floor Hole Ceiling Logistics     FloorHole                      2.0.21
Fluid AWESOME Sink Redux         FluidResourceSinkRedux         1.0.1
Fluid Extras                     AB_FluidExtras                 0.9.0
Fluid Sink and more              FluidSink                      1.0.9
Geothermal Generator Mk+         GeothermalMk                   1.3.1
Geothermal MK0                   GeothermalMK0                  2.0.3
Gravity                          Gravity                        1.0.1
Hover Pack Extensions            HoverPackExtensions            0.3.1
HyperTunnels                     HyperTunnels                   1.0.3
Industrial Evolution             MkPlus                         1.2.8
Industrial Evolution: Libs       MkPlusLibs                     1.0.3
Industrial Evolution: Lite       MkPlusLite                     1.1.4
Infinite Storage Container       InfiniteStorage                3.0.1
Infinite Zoop                    InfiniteZoop                   1.5.15
Inventory Slots 50+              InventorySpace2                2.0.1
Item Spawner                     ItemSpawner                    1.0.23
Just Pause                       JustPause                      1.1.0
Just Stackable Power Pole        JustStackablePole              1.0.0
Kyris Blueprint Function Library KBFL                           1.15.6
Kyris Decor Library              KDecoLib                       2.3.2
Kyris Private Code Library       KPrivateCodeLib                1.10.0
Kyris User Interface Library     KUI                            1.10.0
Linear Motion                    LinearMotion                   2.0.22
Lower Space Whale-Thing Health   NukeTheWhales                  1.0.0
MAM Enhancer                     MAMTips                        1.1.0
Manta Raise                      MantaRaise                     1.0.0
Marcio Common Libs               MarcioCommonLibs               1.1.4
Microwave Power                  MicrowavePower                 0.7.10
MinerMk5                         MinerMk5                       1.4.1
Mk++                             MK22k20                        5.1.5
Mob Spawners                     MobSpawners                    2.0.1
Modpack: All PowerSuit Modules   ArmorModules__Modpack_All      2.0.0
Modular Load Balancers           LoadBalancers                  1.7.11
Modular UI                       ModularUI                      2.0.13
More Swatch Slots                MoreSwatchSlots                1.2.1
No New Label                     NoNewLabel                     1.0.0
Pak Utility Mod                  UtilityMod                     0.7.1
Personal Drones                  PersonalDrones                 1.0.13
Pimp My Factory                  PimpMyFactory                  1.1.2
Pipe Tuner                       PipeTuner                      1.0.2
Pneumatic Fracking Machine       PneumaticFrackingMachine       1.2.0
Power Control Room               PowerControlRoom               1.0.14
PowerSuit                        PowerSuit                      1.2.1
PowerSuit Logistic Modules       LogisticModules                1.0.1
PowerSuit Modules                ArmorModules                   4.1.1
Production Multipliers           ProductionMultipliers          0.3.7
Progressive Trains And Drones    CheapTrains                    3.3.0
PSM: Flight                      ArmorModules_Flight            2.0.0
PSM: Fresh from R&D              ArmorModules_Special           2.0.1
PSM: Mobility                    ArmorModules_Mobility          2.1.0
PSM: Pioneer Protection          ArmorModules_Defense           2.0.0
PSM: Power Generation            ArmorModules_PowerGeneration   2.1.0
PSM: Suit Regulation             ArmorModules_SuitRegulation    2.0.0
Refined Power                    RefinedPower                   3.1.11
RefinedRDLib                     RefinedRDLib                   1.0.18
Remove All Annoyances            RemoveAllAnnoyances            1.1.4
Road Tool                        RoadSplineTool                 1.0.5
RSS2 / Really Simple Signs       RSS                            1.6.5
Satisfactory Helper              SatisfactoryHelper             2.0.5
Simple Underground               UndergroundWorld               1.0.2
SkyUI                            SkyUI                          1.0.3
Small Refinery                   SmallRefinery                  1.0.2
SnapOn                           DirectToSplitter               1.0.8
Soft Clearance for Everything    UniversalSoftClearance         1.0.3
Space Market 2                   SpaceMarket2                   1.0.2
Stackable Machines               StackableMachines              1.0.2
Structural Solutions             SS_Mod                         1.1.17
Super (Alternate) Recipes        AlternateRecipes               1.1.0
TeleJump                         TeleJump                       1.0.5
ThousandContainersCheat          ThousandContainersCheat        1.0.1
Throughput Counter and Limiter   CounterLimiter                 1.1.0
Turrets                          Turrets                        1.0.2
Wall Conveyor Supports           WallConveyorSupports           1.1.1
Wall Pipe Supports               WallPipeSupports               2.1.3
Water Pools+                     WaterPoolsPlus                 1.0.1
X3 Splitter / Merger Pole [MP]   x3_splitter_merger_pole        1.1.
## Additional context
suit flight enhancing modules randomly stop working while they are stacked

**Comment by budak7273** [comment]
See #19

Please open a different post with more info about the flight enhancing modules bug you mentioned in "Additional context"; that isn't related to the suit expander bug, nor is it enough info to really do anything with
