### ISSUE TITLE
No Base Module in Workbench

### ISSUE THREAD

**Issue by Kernoll** [budak7273/ArmorModules#6]
I can't make a base module because there isn't an option in the workbench to do that.  

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Multiplayer?**
If you're playing in multiplayer, if it affects host or clients, etc.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Additional context**

If you crashed, please attach your crash generated by the launcher to this report.
![](https://cdn.discordapp.com/attachments/555782140533407764/738104443849015387/unknown.png)

**Comment by budak7273** [comment]
Have you unlocked the Tier 2 "Armor Module Crafting Components" milestone yet? That's the milestone with the recipes for all of the crafting components.

Any additional details about this issue would be appreciated.

**Comment by Kernoll** [comment]
Rob,

 

I think that was the problem. I had not scrolled to the end of tier 2 to find those.  Wish there was an easier way to scroll through all of the stuff in a tier. Maybe a way to sort it so that the modules that are not finished yet are separate.  Anyway, I’ve got the modded exosuit working now.

 

However, every time I die, I lose all of the modules. I use the mod that lets me keep all of my stuff, but I don’t think that is what causes me to lose the modules.  Wish that one little problem could get worked out.

 

I really appreciate your getting back to me and I really appreciate your work on mods.

Mary/Kernoll

**Comment by budak7273** [comment]
Yeah... I don't think the crafting UI is really intended to have this many items in it. I plan on possibly making a custom crafting station for these, just to get them out of the workbench and equipment workshop.

We're not quite sure what causes the problem with modules vanishing on death right right now, as we haven't been able to reproduce it consistently in testing. If you do find something that seems to cause it consistently, please open another issue report with those details.

Have fun!
