### ISSUE TITLE
[Suggestion] Move Biofuel based suit to Tier 4

### ISSUE THREAD

**Issue by maskedmouse** [budak7273/ArmorModules#7]
I've started a new game and started researching the Biofuel based suit. But in order to build the suit itself you require integrated blade runners which requires 50 motors. Motors are Tier 4 advanced steel. The suit itself is in Tier 2.

In order to start early with the Biofuel suit I'd suggest replacing motors with Modular frames.

**Comment by budak7273** [comment]
Whoops! That's just supposed to be regular blade runners. I will get a patch out that should fix that soon.

I'm embarrassed it took this long to catch that mistake. Thanks for the report, else it would have gone on unreported for even longer.

**Comment by budak7273** [comment]
This should be fixed as of 2.0.5.

Thanks for the report!
