### ISSUE TITLE
Hold to Sprint

### ISSUE THREAD

**Issue by Halfwhit** [budak7273/ArmorModules#9]
When not enabling the "Hold to sprint" option under the game settings, the powersuit recognises sprinting as walking and as such does not consume energy. I would expect the powersuit to respect that setting, allowing the shift key to toggle between walking and sprinting.

**Comment by budak7273** [comment]
The suit keybinds are controlled by the base PowerSuit mod, so the fix will happen on that end. The boosting logic just doesn't account for that setting right now. I'm assuming that the setting will be able to be read the same way the volume sliders can, so it should be possible. It might be a while before this is implemented, though - it will probably end up coming with the update that makes all keybinds configurable.

You stated, "the powersuit recognizes sprinting as walking and as such does not consume energy." Does it still apply the sprinting speed boosts? If you use the Fuel Runners module, for example, it will be very very clear if the speed boosts are applied or not.

**Comment by Halfwhit** [comment]
I can confirm that when holding shift the speed boosts and fuel consumption does indeed apply. Likewise when sprint is toggled on I am indeed getting the boost (but no energy consumption unless it is held down).

**Comment by budak7273** [comment]
Toggle Sprint support added in PowerSuit 0.6.3
